"""
Generates the MDU Sales Training PowerPoint deck.
Reuses the diagrams generated by build_training_doc.py.
Run: python build_training_pptx.py
"""

from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

HERE = Path(__file__).parent
OUT = HERE / "MDU Sales Training Deck.pptx"
DATA_MODEL_PNG = HERE / "_diagram_data_model.png"
LIFECYCLE_PNG = HERE / "_diagram_lifecycle.png"

NAVY = RGBColor(0x1F, 0x3A, 0x68)
ACCENT = RGBColor(0x2E, 0x7D, 0x32)
GRAY = RGBColor(0x55, 0x55, 0x55)
LIGHT = RGBColor(0xF5, 0xF8, 0xFD)
SOFT = RGBColor(0xE8, 0xEE, 0xF7)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
WARN = RGBColor(0xB7, 0x1C, 0x1C)

# Slide dims (16:9 default)
SW = Inches(13.333)
SH = Inches(7.5)


# ---------- helpers ----------

def add_blank(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])


def add_rect(slide, x, y, w, h, fill, line=None):
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, x, y, w, h)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill
    if line is None:
        shape.line.fill.background()
    else:
        shape.line.color.rgb = line
        shape.line.width = Pt(1.0)
    shape.shadow.inherit = False
    return shape


def add_text(slide, x, y, w, h, text, *,
             size=18, bold=False, color=NAVY, align=PP_ALIGN.LEFT,
             anchor=MSO_ANCHOR.TOP, font="Calibri"):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.05)
    tf.margin_right = Inches(0.05)
    tf.margin_top = Inches(0.02)
    tf.margin_bottom = Inches(0.02)
    tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.name = font
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    return tb


def add_bullets(slide, x, y, w, h, items, *, size=18, color=GRAY):
    """items: list of str OR list of (label, body) tuples for label-style bullets."""
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.05)
    tf.margin_right = Inches(0.05)

    for i, item in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.level = 0
        p.space_after = Pt(6)

        if isinstance(item, tuple):
            label, body = item
            r1 = p.add_run()
            r1.text = f"•  {label}: "
            r1.font.name = "Calibri"
            r1.font.size = Pt(size)
            r1.font.bold = True
            r1.font.color.rgb = NAVY
            r2 = p.add_run()
            r2.text = body
            r2.font.name = "Calibri"
            r2.font.size = Pt(size)
            r2.font.color.rgb = color
        else:
            r = p.add_run()
            r.text = f"•  {item}"
            r.font.name = "Calibri"
            r.font.size = Pt(size)
            r.font.color.rgb = color
    return tb


def add_numbered(slide, x, y, w, h, items, *, size=18, color=GRAY):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    for i, item in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(6)
        r = p.add_run()
        r.text = f"{i+1}.  {item}"
        r.font.name = "Calibri"
        r.font.size = Pt(size)
        r.font.color.rgb = color
    return tb


def add_header_bar(slide, section_num, section_title):
    # Thin colored bar on left
    add_rect(slide, Inches(0), Inches(0), Inches(0.25), SH, NAVY)
    # Section eyebrow
    add_text(slide, Inches(0.5), Inches(0.25), Inches(10), Inches(0.3),
             f"SECTION {section_num}", size=12, bold=True, color=ACCENT)
    # Title
    add_text(slide, Inches(0.5), Inches(0.55), Inches(12.3), Inches(0.7),
             section_title, size=30, bold=True, color=NAVY)
    # Underline
    add_rect(slide, Inches(0.5), Inches(1.25), Inches(1.2), Inches(0.05), ACCENT)


def add_footer(slide, page_label):
    add_text(slide, Inches(0.5), Inches(7.05), Inches(12), Inches(0.3),
             "MDU Sales Training  •  Salesforce", size=10, color=GRAY)
    add_text(slide, Inches(11.5), Inches(7.05), Inches(1.5), Inches(0.3),
             page_label, size=10, color=GRAY, align=PP_ALIGN.RIGHT)


def add_table(slide, x, y, w, h, headers, rows, *, header_size=14, body_size=12):
    table_shape = slide.shapes.add_table(len(rows) + 1, len(headers), x, y, w, h)
    table = table_shape.table
    # Header row
    for c, head in enumerate(headers):
        cell = table.cell(0, c)
        cell.fill.solid()
        cell.fill.fore_color.rgb = NAVY
        tf = cell.text_frame
        tf.text = ""
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = head
        run.font.name = "Calibri"
        run.font.size = Pt(header_size)
        run.font.bold = True
        run.font.color.rgb = WHITE
    # Body rows
    for r_i, row in enumerate(rows, start=1):
        for c_i, val in enumerate(row):
            cell = table.cell(r_i, c_i)
            cell.fill.solid()
            cell.fill.fore_color.rgb = LIGHT if r_i % 2 == 1 else WHITE
            tf = cell.text_frame
            tf.text = ""
            tf.word_wrap = True
            p = tf.paragraphs[0]
            run = p.add_run()
            run.text = str(val)
            run.font.name = "Calibri"
            run.font.size = Pt(body_size)
            run.font.color.rgb = GRAY
    return table


# ---------- slide builders ----------

def slide_title(prs):
    s = add_blank(prs)
    # Background
    add_rect(s, 0, 0, SW, SH, NAVY)
    # Accent strip
    add_rect(s, Inches(0), Inches(3.0), SW, Inches(0.08), ACCENT)
    # Title
    add_text(s, Inches(0.8), Inches(2.2), Inches(11.7), Inches(0.9),
             "MDU Sales Training", size=54, bold=True, color=WHITE,
             align=PP_ALIGN.LEFT)
    add_text(s, Inches(0.8), Inches(3.3), Inches(11.7), Inches(0.6),
             "Salesforce: Day-to-Day for the MDU Team", size=22, color=SOFT,
             align=PP_ALIGN.LEFT)
    add_text(s, Inches(0.8), Inches(6.6), Inches(11.7), Inches(0.4),
             "Ubiquity  •  MDU Sales", size=12, color=SOFT, align=PP_ALIGN.LEFT)


def slide_agenda(prs, sections):
    s = add_blank(prs)
    add_header_bar(s, "", "Agenda")
    # Override section number text since this isn't a section
    # (The header bar already shows SECTION blank, fix it)
    # Rebuild header for agenda
    # Clear is hard; redo by adding agenda eyebrow
    add_text(s, Inches(0.5), Inches(1.5), Inches(11), Inches(0.4),
             "Eleven sections, roughly in the order you will use them.",
             size=14, color=GRAY, italic_via_color=False)

    # Two columns of agenda items
    col_w = Inches(6.0)
    col_h = Inches(5.0)
    left_items = sections[:6]
    right_items = sections[6:]

    def render(x, items, start_index):
        tb = s.shapes.add_textbox(x, Inches(2.1), col_w, col_h)
        tf = tb.text_frame
        tf.word_wrap = True
        for i, title in enumerate(items):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.space_after = Pt(12)
            r1 = p.add_run()
            r1.text = f"{start_index + i:>2}.  "
            r1.font.name = "Calibri"
            r1.font.size = Pt(20)
            r1.font.bold = True
            r1.font.color.rgb = ACCENT
            r2 = p.add_run()
            r2.text = title
            r2.font.name = "Calibri"
            r2.font.size = Pt(20)
            r2.font.color.rgb = NAVY

    render(Inches(0.7), left_items, 1)
    render(Inches(7.0), right_items, 7)
    add_footer(s, "Agenda")


def slide_section_divider(prs, num, title, blurb=None):
    s = add_blank(prs)
    add_rect(s, 0, 0, SW, SH, NAVY)
    # Big number on left
    add_text(s, Inches(0.6), Inches(2.0), Inches(3.0), Inches(3.5),
             f"{num:02d}", size=180, bold=True, color=ACCENT, align=PP_ALIGN.LEFT)
    # Title
    add_text(s, Inches(4.0), Inches(2.6), Inches(8.7), Inches(1.0),
             title, size=44, bold=True, color=WHITE, align=PP_ALIGN.LEFT)
    if blurb:
        add_text(s, Inches(4.0), Inches(3.7), Inches(8.7), Inches(2.0),
                 blurb, size=18, color=SOFT, align=PP_ALIGN.LEFT)


def slide_content(prs, section_num, title, *, body_render):
    s = add_blank(prs)
    add_header_bar(s, section_num, title)
    body_render(s)
    add_footer(s, f"Section {section_num}")
    return s


def slide_image(prs, section_num, title, img_path, caption=None):
    s = add_blank(prs)
    add_header_bar(s, section_num, title)
    if caption:
        add_text(s, Inches(0.5), Inches(1.4), Inches(12.3), Inches(0.5),
                 caption, size=14, color=GRAY)
    # Embed image centered
    pic = s.shapes.add_picture(str(img_path), Inches(1.5), Inches(2.0), width=Inches(10.3))
    add_footer(s, f"Section {section_num}")


# Patch: PP_ALIGN doesn't have italic_via_color. Quick wrapper to ignore that kwarg.
_old_add_text = add_text


def add_text(slide, x, y, w, h, text, *, size=18, bold=False, color=NAVY,
             align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, font="Calibri",
             italic_via_color=False):
    return _old_add_text(slide, x, y, w, h, text, size=size, bold=bold,
                         color=color, align=align, anchor=anchor, font=font)


# ---------- build deck ----------

def build():
    prs = Presentation()
    prs.slide_width = SW
    prs.slide_height = SH

    sections = [
        "Why we moved to Salesforce",
        "Logging in and getting around",
        "How the data fits together",
        "Opportunity stages",
        "Daily workflows",
        "Agreements",
        "The MDU Tracker",
        "Reports and dashboards",
        "How SiteTracker fits in",
        "Common gotchas and rules",
        "What is coming next",
    ]

    # 1. Title
    slide_title(prs)

    # 2. Agenda
    slide_agenda(prs, sections)

    # ============ SECTION 1: Why ============
    slide_section_divider(prs, 1, sections[0],
        "From a list in Monday.com to a system that ties pursuits, people, agreements, and builds together.")

    def s1_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.5),
                 "Monday.com was a list. Salesforce is a system.", size=18, color=GRAY)
        add_bullets(s, Inches(0.7), Inches(2.2), Inches(12.0), Inches(4.5), [
            ("One record per property", "the Opportunity is the property pursuit. Everything hangs off it."),
            ("Notes are first class", "every conversation, decision, and update on the Opportunity."),
            ("Agreements tracked separately", "PAL, ROE, EMA, Bulk each get their own record with own status."),
            ("Stages are the source of truth", "moving Opps through stages is how leadership sees pipeline."),
            ("Build tracking stays in SiteTracker", "the Opp does not track construction."),
        ], size=17)
    slide_content(prs, 1, "What changes for you", body_render=s1_a)

    def s1_b(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.5),
                 "What was migrated from Monday.com", size=18, color=GRAY)
        add_bullets(s, Inches(0.7), Inches(2.4), Inches(12.0), Inches(4), [
            "3,229 MDU Opportunities",
            "26 Accounts and 128 Contacts",
            "1,291 Agreements (status carried over from Monday columns)",
            "13,269 historical Notes (every Monday update preserved by author + date)",
        ], size=20)
    slide_content(prs, 1, "What was migrated", body_render=s1_b)

    # ============ SECTION 2: Login / Nav ============
    slide_section_divider(prs, 2, sections[1],
        "Where to log in, how to find the MDU Sales app, and the tabs you will use every day.")

    def s2_a(s):
        add_bullets(s, Inches(0.7), Inches(1.6), Inches(12.0), Inches(2.0), [
            ("Lightning URL", "https://fun-power-747.lightning.force.com"),
            ("Username", "your @ubiquitygp.com Salesforce username"),
            ("If you cannot log in", "Forgot Password on the login page, or ping Cass."),
        ], size=18)
        add_text(s, Inches(0.5), Inches(3.6), Inches(12.3), Inches(0.4),
                 "Switching to the MDU Sales app", size=20, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(4.1), Inches(12.0), Inches(2.5), [
            "Top left, click the App Launcher (nine-dot grid).",
            "Type \"MDU Sales\" and pin it. This is the app you live in day to day.",
            "If you also work Business pursuits, switch to Business Sales from the same launcher.",
        ], size=18)
    slide_content(prs, 2, "Where to log in", body_render=s2_a)

    def s2_b(s):
        add_text(s, Inches(0.5), Inches(1.4), Inches(12.3), Inches(0.4),
                 "Tabs you will use", size=18, color=GRAY)
        add_table(s, Inches(0.5), Inches(1.9), Inches(12.3), Inches(4.8),
                  ["Tab", "What it is", "When to use it"],
                  [
                      ["Opportunities", "Every property pursuit", "Most of your day. Update stage, log notes, manage agreements."],
                      ["Accounts", "Mgmt companies & owner entities", "See all properties tied to one company."],
                      ["Contacts", "People (PMs, owners, leasing, HOA, GCs)", "Find a person, see what properties they touch."],
                      ["Agreements", "PAL, ROE, EMA, Bulk records", "Pipeline view of contracts in flight."],
                      ["Property Locations", "Serviceable properties (address-level)", "One Account can have many Locations."],
                      ["Reports", "Saved reports", "Pull lists for meetings or standups."],
                      ["Dashboards", "Visual rollups", "MDU Sales Dashboard for a snapshot."],
                  ],
                  header_size=13, body_size=12)
    slide_content(prs, 2, "Tabs you will use", body_render=s2_b)

    # ============ SECTION 3: Data Model ============
    slide_section_divider(prs, 3, sections[2],
        "The Opportunity is the center of the universe. Everything else hangs off it.")

    def s3_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.5),
                 "The pieces", size=18, color=GRAY)
        add_bullets(s, Inches(0.7), Inches(2.1), Inches(12.0), Inches(5), [
            ("Account", "property mgmt company or owner entity (Greystar, an LLC)."),
            ("Contact", "an actual person (PM, Owner, HOA, Leasing, GC, Legal, Broker)."),
            ("Opportunity", "the property pursuit. One per property. Where your work lives."),
            ("Opportunity Contact", "links a Contact to an Opportunity with a Role."),
            ("Agreement", "child of the Opportunity. PAL/ROE/EMA/Bulk/etc."),
            ("Property Location", "the serviceable property record. Address, units, parcel."),
            ("Property Unit", "individual unit inside a Location (passive for MDU)."),
            ("SiteTracker Project", "build record in the separate construction org."),
        ], size=15)
    slide_content(prs, 3, "The pieces", body_render=s3_a)

    # Diagram slide
    slide_image(prs, 3, "How the records connect", DATA_MODEL_PNG,
                caption="Account at top, Opportunity in the middle, agreements/notes/SiteTracker fan out from it.")

    def s3_c(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.5),
                 "Why a junction object for Contacts?", size=18, color=GRAY)
        add_text(s, Inches(0.7), Inches(2.3), Inches(11.9), Inches(2.5),
                 "A Property Manager often manages dozens of properties. We need that one Contact "
                 "record connected to every Opportunity she touches, with the role on each. "
                 "Opportunity Contact is what makes that work.",
                 size=20, color=NAVY)
        add_text(s, Inches(0.5), Inches(5.0), Inches(12.3), Inches(0.5),
                 "Practical impact", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(5.5), Inches(12.0), Inches(1.6), [
            "Search Contacts before creating. Reuse, do not duplicate.",
            "On a Contact record, you can see every Opportunity they appear on.",
        ], size=16)
    slide_content(prs, 3, "Why a junction object", body_render=s3_c)

    # ============ SECTION 4: Stages ============
    slide_section_divider(prs, 4, sections[3],
        "How leadership reads the pipeline. Keeping these honest is the most important habit.")

    def s4_a(s):
        add_table(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(5.0),
                  ["Stage", "Prob.", "What it means", "What is required"],
                  [
                      ["Prospecting", "10%", "Property on the radar. Outreach in progress.", "Sales Status"],
                      ["Engaged", "30%", "In real conversation with the property.", "Property contact info"],
                      ["Contract Negotiations", "50%", "Terms being discussed. Agreement language going back and forth.", "Agreement (Create/Review)"],
                      ["ROE Secured", "50%", "Right of Entry locked.", "ROE Agreement signed"],
                      ["Under Contract", "100%", "PAL signed. SiteTracker takes over.", "PAL signed + ST linked"],
                      ["On Hold", "0%", "Pursuit paused.", "Hold Reason"],
                      ["Closed Lost", "0%", "Will not happen.", "Loss Reason"],
                  ],
                  header_size=13, body_size=12)
    slide_content(prs, 4, "Stages and what they mean", body_render=s4_a)

    def s4_b(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "Sales Status (used during Prospecting)", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(2.0), Inches(12.0), Inches(1.7), [
            ("Contact Pending", "we do not yet have property contact info."),
            ("Reached Out, Pending Response", "outreach made, waiting on a reply."),
            ("Research Completed", "background work done, ready to engage."),
        ], size=16)

        add_text(s, Inches(0.5), Inches(3.9), Inches(6.0), Inches(0.4),
                 "Hold Reasons", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(4.4), Inches(6.0), Inches(2.5), [
            "Ownership Change", "Budget or Timing", "Pending Legal Review",
            "Market Conditions", "Other",
        ], size=15)

        add_text(s, Inches(7.0), Inches(3.9), Inches(6.0), Inches(0.4),
                 "Loss Reasons", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(7.2), Inches(4.4), Inches(6.0), Inches(2.5), [
            "Existing Fiber (most common)", "Existing Contract", "Not Interested",
            "No Contact Info", "Chose Another Provider", "Unserviceable", "Other",
        ], size=15)
    slide_content(prs, 4, "Required reasons by stage", body_render=s4_b)

    # Lifecycle diagram
    slide_image(prs, 4, "Stage lifecycle (visual)", LIFECYCLE_PNG,
                caption="Main path along the top. On Hold and Closed Lost are off-ramps from any active stage.")

    # ============ SECTION 5: Workflows ============
    slide_section_divider(prs, 5, sections[4],
        "Step by step for the seven things you will do most often.")

    workflows = [
        ("5.1  Create a new Opportunity", [
            "Opportunities tab, click New.",
            "Pick the MDU record type.",
            "Fill basics: Name (use property name), Account, Stage, Projected Close Date.",
            "Property Details: Units, Property Type, City, State, Zip (required).",
            "If Stage is Prospecting, set a Sales Status.",
            "Save. Start logging notes and adding contacts.",
        ], "Naming: property name first, units second when ambiguous (e.g. \"Olympus Waterford 25\")."),
        ("5.2  Log a note", [
            "Open the Opportunity.",
            "Notes related list (left sidebar), click New.",
            "Short title, write the note, save.",
            "Newest note shows on top.",
        ], "If a teammate opens this Opp in 6 months, the Notes should tell the story."),
        ("5.3  Add a Contact", [
            "Open the Opportunity.",
            "Contacts related list (left sidebar), click New.",
            "Search for the Contact. Reuse existing records, do not duplicate.",
            "Set Role: PM, Owner, Leasing, HOA, GC, Developer, Legal, Broker, Other.",
            "Save.",
        ], "If the Contact does not exist yet, create it from the Contacts tab first, then link."),
        ("5.4  Create an Agreement", [
            "Open the Opportunity.",
            "Agreements related list, click New.",
            "Pick Agreement Type (PAL, ROE, EMA, Bulk, NEMA, etc.).",
            "Set Status (start at Create).",
            "Set Requested Date when it goes out.",
            "Set Signer + Signed Date when it lands.",
            "Add IronClad ID if you have one.",
        ], "PAL is the gateway. Nothing real happens on a property until the PAL is signed."),
        ("5.5  Move to Under Contract", [
            "PAL Agreement Status set to Sign or Completed with Signed Date.",
            "On the Opportunity, change Stage to Under Contract.",
            "Probability auto-sets to 100%.",
            "Build progress now lives in SiteTracker.",
        ], "Once Under Contract, the Opp does not change stage again unless something goes wrong."),
        ("5.6  Put on Hold", [
            "Open the Opportunity.",
            "Change Stage to On Hold.",
            "Set Hold Reason (required).",
            "Add a Note: who paused it, when to revisit.",
            "Save.",
        ], "On Hold is reversible. Use it for real pauses, not stalled outreach."),
        ("5.7  Close as Lost", [
            "Open the Opportunity.",
            "Change Stage to Closed Lost.",
            "Set Loss Reason (required).",
            "Add a Note with detail.",
            "Save.",
        ], "99% of MDU losses are existing fiber. That is fine. Just record it."),
    ]

    for title, steps, callout in workflows:
        def make_render(steps=steps, callout=callout):
            def render(s):
                add_numbered(s, Inches(0.7), Inches(1.5), Inches(12.0), Inches(4.5),
                             steps, size=17)
                # Callout box
                box_y = Inches(5.7)
                add_rect(s, Inches(0.5), box_y, Inches(12.3), Inches(1.0), LIGHT, line=ACCENT)
                add_text(s, Inches(0.7), box_y, Inches(12.0), Inches(0.4),
                         "Tip", size=12, bold=True, color=ACCENT,
                         anchor=MSO_ANCHOR.MIDDLE)
                add_text(s, Inches(0.7), Inches(6.0), Inches(12.0), Inches(0.7),
                         callout, size=14, color=GRAY)
            return render

        slide_content(prs, 5, title, body_render=make_render())

    # ============ SECTION 6: Agreements ============
    slide_section_divider(prs, 6, sections[5],
        "Each Opportunity has its own track of agreements. Most properties end up with several.")

    def s6_a(s):
        add_table(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(5.0),
                  ["Type", "What it does"],
                  [
                      ["PAL", "Property Access License. Gateway agreement. Required before engineering."],
                      ["ROE", "Right of Entry. Physical access to the property for survey and build."],
                      ["EMA", "Easement / marketing access. Often parallel to PAL."],
                      ["Bulk", "Bulk service agreement when the property is paying for all units."],
                      ["NEMA", "Non-exclusive marketing agreement."],
                      ["PAL Addendum", "Modification to an existing PAL."],
                      ["MSA Addendum", "Modification to a master services agreement."],
                      ["2nd ISP NEMA", "When a second ISP is also marketing on the property."],
                  ],
                  header_size=14, body_size=12)
    slide_content(prs, 6, "Agreement types", body_render=s6_a)

    def s6_b(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.5),
                 "Status flow (aligned to IronClad)", size=18, color=GRAY)
        add_bullets(s, Inches(0.7), Inches(2.1), Inches(12.0), Inches(3.5), [
            ("Create", "drafting in progress on our side."),
            ("Review", "out for internal or counterparty review."),
            ("Sign", "signature collection underway."),
            ("Completed", "fully executed."),
            ("Archive", "completed and filed."),
            ("Paused", "stalled, waiting on something external."),
            ("Cancelled", "will not happen."),
        ], size=15)
        add_text(s, Inches(0.5), Inches(5.6), Inches(12.3), Inches(0.5),
                 "IronClad ID", size=18, bold=True, color=ACCENT)
        add_text(s, Inches(0.7), Inches(6.0), Inches(12.0), Inches(1.0),
                 "Populate it when you have it. Going forward, Agreements with no IronClad ID "
                 "show on a cleanup report. Treat it as the audit trail.",
                 size=14, color=GRAY)
    slide_content(prs, 6, "Status flow + IronClad", body_render=s6_b)

    # ============ SECTION 7: Tracker ============
    slide_section_divider(prs, 7, sections[6],
        "The single most useful view in the app. Filtered, paginated, summarized.")

    def s7_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(6.0), Inches(0.4),
                 "What it shows", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(2.0), Inches(6.0), Inches(3.5), [
            "Property name",
            "Stage",
            "SiteTracker Build Status",
            "Owner + RE Assigned",
            "Projected Close Date",
            "Summary bar: Opps, Units, completed Agreements",
            "50/page + Load More",
        ], size=15)

        add_text(s, Inches(7.0), Inches(1.5), Inches(6.0), Inches(0.4),
                 "Filters", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(7.2), Inches(2.0), Inches(6.0), Inches(3.5), [
            ("Owner", "your pipeline or someone else's."),
            ("RE Assigned", "TF, JB, RS, etc."),
            ("Stage", "MDU stages only."),
            ("Date range", "by Projected Close."),
        ], size=15)

        add_text(s, Inches(0.5), Inches(5.6), Inches(12.3), Inches(0.4),
                 "How to use it through the week", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(6.1), Inches(12.0), Inches(1.0), [
            ("Mondays", "filter to your Owner, walk Engaged + Contract Negotiations."),
            ("Mid-week", "scan On Hold for anything ready to re-engage."),
            ("Fridays", "anything closing this month with a stale stage gets a Note + status check."),
        ], size=14)
    slide_content(prs, 7, "Living in the Tracker", body_render=s7_a)

    # ============ SECTION 8: Reports ============
    slide_section_divider(prs, 8, sections[7],
        "Where to look when you need a list, a chart, or a snapshot for leadership.")

    def s8_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "MDU Sales Dashboard", size=20, bold=True, color=ACCENT)
        add_text(s, Inches(0.7), Inches(2.0), Inches(12.0), Inches(0.5),
                 "Six charts, filterable by Opportunity Owner. Open from the Dashboards tab.",
                 size=14, color=GRAY)
        add_bullets(s, Inches(0.7), Inches(2.6), Inches(6.0), Inches(2.5), [
            "Opportunities by Stage",
            "Opportunities by Owner",
            "Opportunities by State",
        ], size=15)
        add_bullets(s, Inches(7.0), Inches(2.6), Inches(6.0), Inches(2.5), [
            "Units by Stage",
            "Stage by Owner Matrix",
            "SiteTracker Coverage",
        ], size=15)

        add_text(s, Inches(0.5), Inches(5.0), Inches(12.3), Inches(0.4),
                 "Campaign Dashboard", size=20, bold=True, color=ACCENT)
        add_text(s, Inches(0.7), Inches(5.5), Inches(12.0), Inches(1.5),
                 "When properties are part of a named initiative (e.g. 9-25 MDU ROE Project), they are "
                 "tagged via Campaign. The Campaign Dashboard shows pipeline progress for just that group.",
                 size=14, color=GRAY)
    slide_content(prs, 8, "Dashboards available to you", body_render=s8_a)

    # ============ SECTION 9: SiteTracker ============
    slide_section_divider(prs, 9, sections[8],
        "Build tracking lives somewhere else. Here is how the two connect.")

    def s9_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.6),
                 "SiteTracker is a separate Salesforce org used by Engineering. We do not track "
                 "build milestones on the Opportunity.",
                 size=16, color=GRAY)
        add_text(s, Inches(0.5), Inches(2.5), Inches(12.3), Inches(0.4),
                 "What you see in MDU Sales", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(3.0), Inches(12.0), Inches(2.5), [
            ("SiteTracker Project ID", "the linking key. Auto-populated by sync."),
            ("SiteTracker URL", "click through to the build record in the SiteTracker org."),
            ("ST Build Status", "shown on the Tracker as a virtual column."),
            ("In SiteTracker checkbox", "yes/no, whether the Opp is linked."),
        ], size=15)
        # Rule of thumb callout
        add_rect(s, Inches(0.5), Inches(5.7), Inches(12.3), Inches(1.3), LIGHT, line=ACCENT)
        add_text(s, Inches(0.7), Inches(5.75), Inches(12.0), Inches(0.4),
                 "Rule of thumb", size=14, bold=True, color=ACCENT)
        add_text(s, Inches(0.7), Inches(6.15), Inches(12.0), Inches(0.9),
                 "If it is about the sale (status, agreements, contacts, conversations) it goes in MDU Sales. "
                 "If it is about the build (FDH activation, lit fiber, install schedule) it lives in SiteTracker.",
                 size=14, color=GRAY)
    slide_content(prs, 9, "What you see and where", body_render=s9_a)

    def s9_b(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "How the sync works", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(2.0), Inches(12.0), Inches(3.0), [
            "GitHub Action runs every night at 2am Central, syncing SiteTracker Projects into MDU Sales.",
            "Match key is property name + Agreement Name. New projects link automatically.",
            "If a property has no link after construction starts, flag it to Cass.",
        ], size=16)
    slide_content(prs, 9, "How the sync works", body_render=s9_b)

    # ============ SECTION 10: Gotchas ============
    slide_section_divider(prs, 10, sections[9],
        "The validation rules and quirks that catch people their first week.")

    def s10_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "Validation rules you will hit", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(2.0), Inches(12.0), Inches(4.5), [
            ("City, State, Zip required", "you cannot save without all three. Set them at creation."),
            ("Sales Status required when Prospecting", "pick Contact Pending, Reached Out, or Research Completed."),
            ("Hold Reason required when On Hold", "pick a reason."),
            ("Loss Reason required when Closed Lost", "pick a reason."),
            ("Agreement Name is unique", "do not duplicate. If you see a dupe error, search first."),
        ], size=16)
    slide_content(prs, 10, "Validation rules", body_render=s10_a)

    def s10_b(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "Habits to keep", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(2.0), Inches(12.0), Inches(2.5), [
            "Do not edit Close Date. Use Projected Close Date for forecasting.",
            "Reuse existing Contacts before creating new ones.",
            "Use Notes for every conversation. Pipeline reviews depend on it.",
            "Move the Stage when reality changes. Stale stages are worse than empty ones.",
        ], size=15)

        add_text(s, Inches(0.5), Inches(4.6), Inches(12.3), Inches(0.4),
                 "If something looks wrong", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(5.1), Inches(12.0), Inches(2.0), [
            "Cannot find an Opp? Check Closed Lost and On Hold filters.",
            "Contact on the wrong Account? Fix the Contact, not the Opp link.",
            "Missing SiteTracker link on a built property? Send the property name to Cass.",
            "Validation rule blocking you? Screenshot the error, ping Cass, do not work around it.",
        ], size=14)
    slide_content(prs, 10, "Habits and what to do when stuck", body_render=s10_b)

    # ============ SECTION 11: What's next ============
    slide_section_divider(prs, 11, sections[10],
        "Where this is going over the next few months.")

    def s11_a(s):
        add_bullets(s, Inches(0.7), Inches(1.5), Inches(12.0), Inches(5.5), [
            ("IronClad sync", "agreement status flows automatically once API access lands."),
            ("Monday.com retirement", "once the team is comfortable here, Monday.com goes away for MDU."),
            ("ROE & SAQ Excel trackers fold in", "become Salesforce reports backed by Agreement records."),
            ("Investor PAL report", "a PAL pipeline tile on the MDU home page for fundraising."),
            ("Tracker enhancements", "more filters, saved views per user, deeper SiteTracker integration."),
        ], size=17)
    slide_content(prs, 11, "Coming next", body_render=s11_a)

    # ============ Quick Reference ============
    slide_section_divider(prs, 12, "Quick reference",
        "The cheat-sheet you keep at your desk.")

    def qr_a(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "Required when you change Stage", size=18, bold=True, color=ACCENT)
        add_table(s, Inches(0.5), Inches(2.0), Inches(12.3), Inches(2.5),
                  ["Stage", "Required field"],
                  [
                      ["Prospecting", "Sales Status"],
                      ["On Hold", "Hold Reason"],
                      ["Closed Lost", "Loss Reason"],
                      ["Under Contract", "PAL Agreement marked Signed"],
                  ],
                  header_size=14, body_size=13)

        add_text(s, Inches(0.5), Inches(4.8), Inches(12.3), Inches(0.4),
                 "Who to ask", size=18, bold=True, color=ACCENT)
        add_bullets(s, Inches(0.7), Inches(5.3), Inches(12.0), Inches(1.7), [
            ("Salesforce questions, validation errors, missing data", "Cass"),
            ("Agreement language and IronClad", "Taylor"),
            ("SiteTracker / build status", "Engineering team"),
            ("Pipeline strategy and stage definitions", "your sales lead"),
        ], size=14)
    slide_content(prs, 12, "Required fields + escalation", body_render=qr_a)

    def qr_b(s):
        add_text(s, Inches(0.5), Inches(1.5), Inches(12.3), Inches(0.4),
                 "Where things live", size=18, bold=True, color=ACCENT)
        add_table(s, Inches(0.5), Inches(2.0), Inches(12.3), Inches(4.8),
                  ["If you want to...", "Go to..."],
                  [
                      ["See your pipeline at a glance", "MDU Sales Dashboard"],
                      ["Walk every active Opp in your name", "MDU Tracker, filter by Owner = you"],
                      ["See agreements in flight", "Agreements tab, MDU Agreements list view"],
                      ["Find a Property Manager", "Contacts tab, search by name"],
                      ["See all properties for a company", "Account record, Opportunities related list"],
                      ["Check construction status", "SiteTracker URL on the Opportunity"],
                      ["Run a list for a meeting", "Reports tab, MDU Sales Reports folder"],
                  ],
                  header_size=14, body_size=13)
    slide_content(prs, 12, "Where things live", body_render=qr_b)

    # ============ Closing ============
    s = add_blank(prs)
    add_rect(s, 0, 0, SW, SH, NAVY)
    add_rect(s, Inches(0), Inches(3.0), SW, Inches(0.08), ACCENT)
    add_text(s, Inches(0.8), Inches(2.4), Inches(11.7), Inches(0.9),
             "Questions?", size=64, bold=True, color=WHITE, align=PP_ALIGN.LEFT)
    add_text(s, Inches(0.8), Inches(3.4), Inches(11.7), Inches(0.6),
             "Send anything that comes up after the session to Cass.",
             size=22, color=SOFT, align=PP_ALIGN.LEFT)
    add_text(s, Inches(0.8), Inches(6.6), Inches(11.7), Inches(0.4),
             "MDU Sales Training", size=12, color=SOFT, align=PP_ALIGN.LEFT)

    prs.save(OUT)
    print(f"Wrote: {OUT}")


if __name__ == "__main__":
    build()
